function Image_hexcode () {
    Philip_variation_1_1 = assets.image`Philip_1`
    Philip_variation_2_1 = assets.image`Philip_2`
    Philip_variation_3_1 = assets.image`Philip_3`
    philip_1 = assets.image`Philip_4`
    navi_variation_3_1 = assets.image`Navi_1`
    navi_1 = assets.image`Navi_2`
    navi_variation_1_1 = assets.image`Navi_3`
    navi_variation_2_1 = assets.image`Navi_4`
    navi_variation_4_1 = assets.image`Navi_5`
    navi_variation_4_1_1 = assets.image`Navi_6`
    navi_variation_5_1 = assets.image`Navi_7`
    navi_variation_5_1_1 = assets.image`Navi_8`
    navi_variation_6_1 = assets.image`Navi_9`
    navi_variation_6_1_1 = assets.image`Navi_16`
    navi_variation_7_1 = assets.image`Navi_11`
    navi_variation_7_1_1 = assets.image`Navi_12`
    navi_variation_8_1 = assets.image`Navi_13`
    navi_variation_9_1 = assets.image`Navi_14`
    navi_variation_9_1_1 = assets.image`Navi_15`
    Jinny_variation_3_1 = assets.image`Jinny_1`
    Jinny_variation_4_1 = assets.image`Jinny_2`
    Jinny_variation_4_1_1 = assets.image`Jinny_3`
    Jinny_variation_3_1_1 = assets.image`Jinny_4`
    Jinny_1 = assets.image`Jinny_5`
    Jinny_1_1 = assets.image`Jinny_6`
    Jinny_variation_1_1 = assets.image`Jinny_7`
    Jinny_variation_1_1_1 = assets.image`Jinny_8`
    Jinny_variation_2_1 = assets.image`Jinny_9`
    Jinny_variation_2_1_1 = assets.image`Jinny_10`
    Jay_variation_1_2 = assets.image`Jay_1`
    Jay_variation_1_1_2 = assets.image`Jay_2`
    Jay_variation_3_2 = assets.image`Jay_3`
    Jay_variation_3_1_2 = assets.image`Jay_4`
    Jay_variation_4_2 = assets.image`Jay_5`
    Jay_variation_4_1_2 = assets.image`Jay_6`
    Harry_variation_1_1 = assets.image`Harry_1`
    Harry_1 = assets.image`Harry_2`
    Harry_1_1 = assets.image`Harry_3`
    Harry_variation_2_1 = assets.image`Harry_4`
    Harry_variation_1_1_1 = assets.image`Harry_5`
    hado_variation_1_1 = assets.image`Hado_1`
    hado_variation_1_8bit = assets.image`Hado_2`
    hado_variation_2_8bit = assets.image`Hado_3`
    hado_variation_3_8bit = assets.image`Hado_4`
    Grace_variation_1_2 = assets.image`Grace_1`
    Grace_variation_1_1_2 = assets.image`Grace_2`
    Grace_variation_2_2 = assets.image`Grace_3`
    Grace_variation_2_1_2 = assets.image`Grace_4`
    Grace_variation_3_2 = assets.image`Grace_8`
    Grace_variation_3_1_2 = assets.image`Grace_7`
    Grace_variation_4_2 = assets.image`Grace_5`
    Grace_variation_4_1_2 = assets.image`Grace_6`
    Untitled3_1 = assets.image`Myrobot_background`
}
let Untitled3_1: Image = null
let Grace_variation_4_1_2: Image = null
let Grace_variation_4_2: Image = null
let Grace_variation_3_1_2: Image = null
let Grace_variation_3_2: Image = null
let Grace_variation_2_1_2: Image = null
let Grace_variation_2_2: Image = null
let Grace_variation_1_1_2: Image = null
let Grace_variation_1_2: Image = null
let hado_variation_3_8bit: Image = null
let hado_variation_2_8bit: Image = null
let hado_variation_1_8bit: Image = null
let hado_variation_1_1: Image = null
let Harry_variation_1_1_1: Image = null
let Harry_variation_2_1: Image = null
let Harry_1_1: Image = null
let Harry_1: Image = null
let Harry_variation_1_1: Image = null
let Jay_variation_4_1_2: Image = null
let Jay_variation_4_2: Image = null
let Jay_variation_3_1_2: Image = null
let Jay_variation_3_2: Image = null
let Jay_variation_1_1_2: Image = null
let Jay_variation_1_2: Image = null
let Jinny_variation_2_1_1: Image = null
let Jinny_variation_2_1: Image = null
let Jinny_variation_1_1_1: Image = null
let Jinny_variation_1_1: Image = null
let Jinny_1_1: Image = null
let Jinny_1: Image = null
let Jinny_variation_3_1_1: Image = null
let Jinny_variation_4_1_1: Image = null
let Jinny_variation_4_1: Image = null
let Jinny_variation_3_1: Image = null
let navi_variation_9_1_1: Image = null
let navi_variation_9_1: Image = null
let navi_variation_8_1: Image = null
let navi_variation_7_1_1: Image = null
let navi_variation_7_1: Image = null
let navi_variation_6_1_1: Image = null
let navi_variation_6_1: Image = null
let navi_variation_5_1_1: Image = null
let navi_variation_5_1: Image = null
let navi_variation_4_1_1: Image = null
let navi_variation_4_1: Image = null
let navi_variation_2_1: Image = null
let navi_variation_1_1: Image = null
let navi_1: Image = null
let navi_variation_3_1: Image = null
let philip_1: Image = null
let Philip_variation_3_1: Image = null
let Philip_variation_2_1: Image = null
let Philip_variation_1_1: Image = null
Image_hexcode()
scene.setBackgroundImage(assets.image`Myrobot_background`)
